version: '3'
services:
  web:
    image: rag_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql-server
    hostname: db
    environment:
      MYSQL_DATABASE: technical
      MYSQL_PASSWORD: root
    ports:
      - "3306"
    # network_mode: host